# Generated by Django 5.0.3 on 2024-03-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SearchResult',
        ),
    ]
